name: Continuous Integration

on:
  push:
    branches:
      - main
      - 'G*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up JDK 17 and Verify Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: mvn dependency:resolve
        name: Verify Dependencies

      - name: Build with Maven
        run: mvn -B clean install

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: mvn test